[2023-08-01 11:03:54,288] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T11:03:51.954830+00:00 [queued]>
[2023-08-01 11:03:54,295] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T11:03:51.954830+00:00 [queued]>
[2023-08-01 11:03:54,295] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 11:03:54,295] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-01 11:03:54,296] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 11:03:54,316] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): stations_data_to_BQ> on 2023-08-01 11:03:51.954830+00:00
[2023-08-01 11:03:54,322] {standard_task_runner.py:52} INFO - Started process 2965 to run task
[2023-08-01 11:03:54,324] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_BigQuery', 'stations_data_to_BQ', 'manual__2023-08-01T11:03:51.954830+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpibnozv96', '--error-file', '/tmp/tmpp_ook4p8']
[2023-08-01 11:03:54,325] {standard_task_runner.py:80} INFO - Job 166: Subtask stations_data_to_BQ
[2023-08-01 11:03:54,378] {task_command.py:370} INFO - Running <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T11:03:51.954830+00:00 [running]> on host a6bbb8f7ba0b
[2023-08-01 11:03:54,481] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_BigQuery
AIRFLOW_CTX_TASK_ID=stations_data_to_BQ
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T11:03:51.954830+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T11:03:51.954830+00:00
[2023-08-01 11:03:54,483] {logging_mixin.py:115} INFO - 
 heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyy
[2023-08-01 11:03:56,700] {logging_mixin.py:115} INFO - 
 working?
[2023-08-01 11:03:56,702] {logging_mixin.py:115} INFO - Error: Unable to locate credentials
[2023-08-01 11:03:56,702] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 11:03:56,955] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_BigQuery, task_id=stations_data_to_BQ, execution_date=20230801T110351, start_date=20230801T110354, end_date=20230801T110356
[2023-08-01 11:03:57,065] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 11:03:57,112] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
