[2023-08-01 11:05:32,703] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T11:05:31.615853+00:00 [queued]>
[2023-08-01 11:05:32,741] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T11:05:31.615853+00:00 [queued]>
[2023-08-01 11:05:32,741] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 11:05:32,741] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-01 11:05:32,741] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 11:05:33,273] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): stations_data_to_BQ> on 2023-08-01 11:05:31.615853+00:00
[2023-08-01 11:05:33,284] {standard_task_runner.py:52} INFO - Started process 3056 to run task
[2023-08-01 11:05:33,291] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_BigQuery', 'stations_data_to_BQ', 'manual__2023-08-01T11:05:31.615853+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5s6pfhfb', '--error-file', '/tmp/tmpfo7nsdrg']
[2023-08-01 11:05:33,294] {standard_task_runner.py:80} INFO - Job 169: Subtask stations_data_to_BQ
[2023-08-01 11:05:33,448] {task_command.py:370} INFO - Running <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T11:05:31.615853+00:00 [running]> on host a6bbb8f7ba0b
[2023-08-01 11:05:33,601] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_BigQuery
AIRFLOW_CTX_TASK_ID=stations_data_to_BQ
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T11:05:31.615853+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T11:05:31.615853+00:00
[2023-08-01 11:05:33,604] {logging_mixin.py:115} INFO - 
 heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyy
[2023-08-01 11:05:35,807] {logging_mixin.py:115} INFO - 
 working?
[2023-08-01 11:05:35,808] {logging_mixin.py:115} INFO - Error: Unable to locate credentials
[2023-08-01 11:05:35,809] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 11:05:36,133] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_BigQuery, task_id=stations_data_to_BQ, execution_date=20230801T110531, start_date=20230801T110532, end_date=20230801T110536
[2023-08-01 11:05:36,274] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 11:05:36,319] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
