[2023-08-02 09:18:12,521] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T09:18:10.718627+00:00 [queued]>
[2023-08-02 09:18:12,530] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T09:18:10.718627+00:00 [queued]>
[2023-08-02 09:18:12,530] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:18:12,530] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 09:18:12,530] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:18:13,137] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_weather_data> on 2023-08-02 09:18:10.718627+00:00
[2023-08-02 09:18:13,144] {standard_task_runner.py:52} INFO - Started process 9645 to run task
[2023-08-02 09:18:13,146] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_weather_data', 'manual__2023-08-02T09:18:10.718627+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmprqz5x3sz', '--error-file', '/tmp/tmp6hco6y0n']
[2023-08-02 09:18:13,147] {standard_task_runner.py:80} INFO - Job 303: Subtask load_weather_data
[2023-08-02 09:18:13,226] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T09:18:10.718627+00:00 [running]> on host 656341a29da6
[2023-08-02 09:18:13,459] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T09:18:10.718627+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T09:18:10.718627+00:00
[2023-08-02 09:18:13,981] {logging_mixin.py:115} INFO - 
DataFrame push into xcom.
[2023-08-02 09:18:13,995] {logging_mixin.py:115} INFO - 
DATAFRAME SHAPE : (13, 11)
[2023-08-02 09:18:13,995] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-02 09:18:14,051] {logging_mixin.py:115} INFO - Error: (psycopg2.ProgrammingError) can't adapt type 'DataFrame'
[SQL: DELETE FROM xcom WHERE xcom.key = %(key_1)s AND xcom.run_id = %(run_id_1)s AND xcom.task_id = %(task_id_1)s AND xcom.dag_id = %(dag_id_1)s AND xcom.map_index = %(map_index_1)s]
[parameters: {'key_1':     precipitation  rain  ... snow_depth               time_period
0             0.8   0.3  ...        0.0 2023-08-01 16:30:00+02:00
1             0.8  ... (647 characters truncated) ...          0.8   0.3  ...        0.0 2023-08-02 01:00:00+02:00
12            0.8   0.3  ...        0.0 2023-08-02 01:30:00+02:00

[13 rows x 11 columns], 'run_id_1': 'manual__2023-08-02T09:18:10.718627+00:00', 'task_id_1': 'load_weather_data', 'dag_id_1': 'S3_to_BigQuery', 'map_index_1': -1}]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2023-08-02 09:18:14,051] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 09:18:14,063] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=load_weather_data, execution_date=20230802T091810, start_date=20230802T091812, end_date=20230802T091814
[2023-08-02 09:18:14,121] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 09:18:14,170] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
