[2023-08-02 05:56:47,463] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_postgres.load_weather_data manual__2023-08-02T05:56:45.139303+00:00 [queued]>
[2023-08-02 05:56:47,471] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_postgres.load_weather_data manual__2023-08-02T05:56:45.139303+00:00 [queued]>
[2023-08-02 05:56:47,471] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 05:56:47,471] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 05:56:47,471] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 05:56:47,538] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_weather_data> on 2023-08-02 05:56:45.139303+00:00
[2023-08-02 05:56:47,545] {standard_task_runner.py:52} INFO - Started process 238 to run task
[2023-08-02 05:56:47,550] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_postgres', 'load_weather_data', 'manual__2023-08-02T05:56:45.139303+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpas9c__c3', '--error-file', '/tmp/tmpxilafsvo']
[2023-08-02 05:56:47,551] {standard_task_runner.py:80} INFO - Job 236: Subtask load_weather_data
[2023-08-02 05:56:47,735] {task_command.py:370} INFO - Running <TaskInstance: s3_to_postgres.load_weather_data manual__2023-08-02T05:56:45.139303+00:00 [running]> on host 656341a29da6
[2023-08-02 05:56:47,826] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_postgres
AIRFLOW_CTX_TASK_ID=load_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T05:56:45.139303+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T05:56:45.139303+00:00
[2023-08-02 05:56:47,827] {logging_mixin.py:115} INFO - 
 heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyy
[2023-08-02 05:56:48,427] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-02 05:56:48,774] {logging_mixin.py:115} INFO - Error: Could not create the table because it already exists. Change the if_exists parameter to 'append' or 'replace' data.
[2023-08-02 05:56:48,777] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 05:56:48,817] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_postgres, task_id=load_weather_data, execution_date=20230802T055645, start_date=20230802T055647, end_date=20230802T055648
[2023-08-02 05:56:48,885] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 05:56:48,961] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
